# Generated by Django 5.1.4 on 2025-01-07 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_category_updated_at_expense_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='split_with',
        ),
        migrations.AddField(
            model_name='expense',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='my_app.group'),
        ),
        migrations.AddField(
            model_name='expense',
            name='split_type',
            field=models.CharField(choices=[('EQUAL', 'Equal'), ('PERCENTAGE', 'Percentage'), ('RATIO', 'Ratio')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='settlement',
            name='settled_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(choices=[('HOSTEL_ROOMMATES', 'Hostel Roommates'), ('PROJECT_TEAMS', 'Project Teams'), ('TRIP_GROUPS', 'Trip Groups')], default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('COMPLETED', 'Complted')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='settlement_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('ONLINE', 'Online')], max_length=255, null=True),
        ),
    ]
